routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Intervention\Image\Facades\Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth'])->group(function () {
    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_view');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_edit');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::post('/', [UserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_store');

        Route::delete('/{user}', [UserController::class, 'destroy'])
            ->name('delete')
            ->middleware(['permission:user_delete', 'check.user']);

        Route::put('/{id}', [UserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('users/{id}', [UserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_show');
    });

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_view');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_edit');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_store');

        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:role_delete');

        Route::put('/{id}', [RoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('users/{id}', [RoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_show');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_view');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_edit');

        Route::put('/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::post('/', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_store');

        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:product_delete');

        Route::get('/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_show');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_view');

        Route::get('/create', [CategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::post('/', [CategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_store');

        Route::get('/list', [CategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_view');

        Route::get('/edit/{id}', [CategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_edit');

        Route::put('/{category}', [CategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::delete('/{category}', [CategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'birthday',
        'address',
        'phone_number',
        'gender',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_user', 'user_id', 'role_id');
    }

    public function scopeWithNameEmail($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%')
            ->orWhere('email', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithRoleId($query, $roleId)
    {
        return $roleId ? $query->WhereHas('roles', function ($q) use ($roleId) {
            $q->where('roles.id', $roleId);
        }) : null;
    }

    public function syncRole($roleId)
    {
        return $this->roles()->sync($roleId);
    }

    public function attachRole($roleId)
    {
        return $this->roles()->attach($roleId);
    }

    public function detachRole()
    {
        return $this->roles()->detach();
    }
    // Chuyen qua repo
    public function getUserRole($id)
    {
        return $this->roles()->where('user_id', $id)->pluck('role_id');
    }

    public function hasRole($role)
    {
//        if ($this->roles->contains('name', $role)) {
//            return true ;
//        }
//        return false;

        return $this->roles->contains('name', $role);
    }

    public function hasPermission($permission)
    {
        foreach ($this->roles as $role) {
            if ($role->permissions->contains('name', $permission)) {
                return true;
            }
        }
        return false;
    }

    public function isSuperAdmin()
    {
//        return $this->roles->contains('name', 'super_admin');
        return $this->hasRole('super_admin');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\UserCollection;
use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class UserController extends Controller
{
    protected $user;

    /**
     * @param $user
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function index()
    {
        $users = $this->user->paginate(5);
        $usersCollection = new UserCollection($users);
        return response()->json([
            'data' => $usersCollection,

        ], Response::HTTP_OK);
    }

    public function store(Request $request)
    {
        $dataCreate = $request->all();
        $user = User::create($dataCreate);
        $postResource = new UserResource($user);
        return $this->sendResponse($postResource, "Thêm thành công");
    }

    public function show($id)
    {
        $user = User::findOrFail($id);
        $postResource = new UserResource($user);
        return $this->sendResponse($postResource, 'Yêu cầu thành công');
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $dataUpdate = $request->all();
        $user->update($dataUpdate);
        return $this->sendResponse(new UserResource($user), 'Cập nhật thành công');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return $this->sendResponse(new UserResource($user), 'Xóa thành công!');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\UpdateUserRequest;
use App\Http\Requests\User\UserRequest;
use App\Services\RoleService;
use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class UserController extends Controller
{
    protected RoleService $roleService;

    protected UserService $userService;

    public function __construct(UserService $userService, RoleService $roleService)
    {
        $this->userService = $userService;

        $this->roleService = $roleService;

        View::share('roles', $this->roleService->getAll());
    }

    public function index(Request $request)
    {
        $users = $this->userService->getAllUser($request);

        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(UserRequest $request)
    {
        $this->userService->store($request);

        return redirect()->route('users.index');
    }

    public function show($id)
    {
        $user = $this->userService->getById($id);

        return view('admin.users.show', compact('user'));
    }

    public function edit($id)
    {
        $user = $this->userService->getById($id);

        $roleIds = $this->userService->getRoleIdUser($id);

        return view('admin.users.edit', compact('user', 'roleIds'));
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $this->userService->update($request, $id);

        return redirect()->route('users.index');
    }

    public function destroy($id)
    {
        $this->userService->delete($id);

        return redirect()->route('users.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Create User</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">User</li>
                </ol>

                <div class="container">
                    <div class="row justify-content-center">
                        <form action="{{ route('users.store') }}" method="POST">
                            @csrf
                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Name</label>
                                    <input name="name" type="text" class="form-control" placeholder="Name..."
                                           value="{{old('name')}}">
                                    @error('name')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Email</label>
                                    <input autocomplete="off" name="email" type="email" class="form-control"
                                           placeholder="Email..." value="{{old('email')}}">
                                    @error('email')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Birthday</label>
                                    <input name="birthday" type="date" class="form-control"
                                           placeholder="Birthday..." value="{{old('birthday')}}">
                                    @error('birthday')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Address</label>
                                    <input name="address" type="text" class="form-control"
                                           placeholder="Address..." value="{{old('address')}}">
                                    @error('address')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Phone Number</label>
                                    <input name="phone_number" type="text" class="form-control"
                                           placeholder="Phone Number +84 ..." value="{{old('phone_number')}}">
                                    @error('phone_number')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Gender</label>
                                    <div>
                                        <input type="radio" name="gender" value="0" checked> Male<br>
                                        <input type="radio" name="gender" value="1"> Female<br>
                                    </div>
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Password</label>
                                    <input autocomplete="off" name="password" type="password" class="form-control"
                                           placeholder="Password...">
                                    @error('password')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Role</label>
                                <div class="form">
                                    @foreach($roles as $role)
                                        <div class="row">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox"
                                                       name="display_name_permission[]" value="{{ $role->id }}">
                                                <label class="form-check-label" for="flexCheckDefault">
                                                    {{ $role->display_name }}
                                                </label>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                                <button type="submit" class="btn btn-success">Create User</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Update User</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">User</li>
                </ol>

                <div class="container">
                    <div class="row justify-content-center">
                        <form action="{{ route('users.update', $user->id) }}" method="POST" class="container">
                            @method('PUT')
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Name</label>
                                <input type="text" class="form-control" name="name" value="{{$user->name}}">
                                @error('name')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Email</label>
                                <input autocomplete="off" type="text" class="form-control" name="email"
                                       value="{{$user->email}}">
                                @error('email')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Birthday</label>
                                <input type="text" class="form-control" name="birthday"
                                       value="{{$user->birthday}}">
                                @error('birthday')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Address</label>
                                <input type="text" class="form-control" name="address"
                                       value="{{$user->address}}">
                                @error('address')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Phone number</label>
                                <input type="text" class="form-control" name="phone_number"
                                       value="{{$user->phone_number}}">
                                @error('phone_number')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>


                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Gender</label>
                                    <div>
                                        <input type="radio" name="gender"
                                               value="0" {{ $user->gender == "0" ? 'checked' : '' }}> Male<br>
                                        <input type="radio" name="gender"
                                               value="1" {{ $user->gender == "1" ? 'checked' : '' }} > Female<br>
                                    </div>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Password</label>
                                <input type="password" class="form-control" name="password"
                                       placeholder="Password...">
                                @error('password')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Role</label>
                                <div class="form">
                                    @foreach($roles as $r)
                                        <div class="row">
                                            <div class="form-check">
                                                <input
                                                    {{ $roleIds->contains($r->id) ? 'checked' : '' }} class="form-check-input"
                                                    type="checkbox"
                                                    name="display_name_permission[]" value="{{ $r->id }}">
                                                <label class="form-check-label" for="flexCheckDefault">
                                                    {{ $r->display_name }}
                                                </label>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <button class="btn btn-success" type="submit">Update Role</button>
                        </form>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Users Management</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">All Users</li>
                </ol>
                <div class="container-fluid px-4">
                    @hasPermission('user_create')
                    <a href="{{ route('users.create') }}" class="btn btn-success">Create New User</a>
                    @endhasPermission
                    <div class="row justify-content-center">
                        <form method="GET" class="col-md-5 m-md-3 d-flex">
                            <select name="role_id" class=" form-control col-md-2 mr-2"
                                    aria-label="Default select example">
                                <option value=" " selected>Roles</option>
                                @foreach($roles as $role)
                                    <option {{ $role->id == request('role_id') ? 'selected' : '' }}
                                            value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>

                            <input type="search" name="name" value="{{ request('name') }}" class="form-control"
                                   placeholder="search ...">
                            <button type="submit" class="btn btn-primary">
                                search
                            </button>
                        </form>
                    </div>

                    <div class="row justify-content-center">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Birthday</th>
                                <th scope="col">Address</th>
                                <th scope="col">Phone number</th>
                                <th scope="col">Gender</th>
                                <th scope="col">Roles</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th scope="row">{{$user->id}}</th>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->birthday}}</td>
                                    <td>{{$user->address}}</td>
                                    <td>{{$user->phone_number}}</td>
                                    <td>
                                        {{ $user->gender == 0 ? 'male' : 'female' }}
                                    </td>
                                    <td>
                                        @foreach($user->roles as $role)
                                            <span style="font-size: 12px"
                                                  class="badge badge-success">{{ $role->display_name }}</span>
                                        @endforeach
                                    </td>

                                    <td>
                                        @hasPermission('user_show')
                                        <a href="{{route('users.show',$user->id)}}" class="btn btn-primary"><i
                                                class="far fa-eye"></i></a>
                                        @endhasPermission
                                        @hasPermission('user_edit')
                                        <a href="{{route('users.edit',$user->id)}}" class="btn btn-success"><i
                                                class="far fa-edit"></i></a>
                                        @endhasPermission
                                        @hasPermission('user_delete')
                                        <button type="submit" class="btn btn-danger btn-delete"
                                                onclick="deleteUser({{$user->id}})"><i
                                                class="fas fa-trash-alt"></i></button>
                                        @endhasPermission
                                        <form action="{{ route('users.delete', $user->id)}}" id="form-{{$user->id}}"
                                              method="POST" style="display: none">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="container-fluid">
                            {{$users->links()}}
                        </div>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script>
        function deleteUser(id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    event.preventDefault();
                    document.getElementById('form-' + id).submit();
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            })
        }
    </script>
@endpush